const chickens = [
    {
        "copyright": {
            "name": "chicken lessons",
            "author": "Anonymous",
            "authorLink": "https://poly.pizza/u/Anonymous",
            "license": "CC-BY",
            "licenseLink": "https://creativecommons.org/licenses/by/3.0/",
            "source": "https://poly.pizza/m/2tjmDzIm_Yw",
        },
        "path": "leo",
        "name": "Leo",
        "shortDescription": "Smartest Chicken in the World",
        "description": "Meet Leo, the crown jewel of The Chicken Market. Leo is not just a chicken; he is an extraordinary companion with a level of intelligence that surpasses all others in the avian world. Raised with exceptional care and trained to the highest standards, Leo demonstrates remarkable problem-solving skills and interactive communication abilities. His superior intellect is matched by his gentle and sociable nature, making him the perfect addition to any home. Experience the unique joy of adopting Leo, and enjoy the unparalleled companionship that only the smartest chicken can provide.",
        "imageCount": 3,
        "price": 199
    },
    {
        "copyright": {
            "name": "Chicken",
            "author": "jeremy",
            "authorLink": "https://poly.pizza/u/jeremy",
            "license": "CC-BY",
            "licenseLink": "https://creativecommons.org/licenses/by/3.0/",
            "source": "https://poly.pizza/m/1YE8U35HXsI",
        },
        "path": "cluck_norris",
        "name": "Cluck Norris",
        "shortDescription": "Chicken of Justice",
        "description": "Cluck Norris is a chicken with a mission. He is a master of martial arts and a legend in the world of poultry. Cluck Norris has dedicated his life to protecting the innocent and fighting for justice. With his lightning-fast reflexes and unbeatable strength, Cluck Norris is a force to be reckoned with. He is a true hero and a symbol of hope for chickens everywhere. Adopt Cluck Norris today and join him in his quest to make the world a better place.",
        "imageCount": 3,
        "price": 149
    },
    {
        "copyright": {
            "name": "Hen",
            "author": "Poly by Google",
            "authorLink": "https://poly.pizza/u/Poly%20by%20Google",
            "license": "CC-BY",
            "licenseLink": "https://creativecommons.org/licenses/by/3.0/",
            "source": "https://poly.pizza/m/8Unya0rw9tR",
        },
        "path": "destroyer_of_worlds",
        "name": "Destroyer of Worlds",
        "shortDescription": "Hen of Doom",
        "description": "Destroyer of Worlds is a hen like no other. She is a creature of pure chaos and destruction, with a thirst for power that knows no bounds. The Destroyer of Worlds has laid waste to entire civilizations and brought empires to their knees. Her fiery gaze strikes fear into the hearts of all who dare to oppose her. Adopt the Destroyer of Worlds today and witness the awesome power of the Hen of Doom.",
        "imageCount": 3,
        "price": 249
    },
    {
        "copyright": {
            "name": "chicken",
            "author": "Maf'j Alvarez",
            "authorLink": "https://poly.pizza/u/Maf'j%20Alvarez",
            "license": "CC-BY",
            "licenseLink": "https://creativecommons.org/licenses/by/3.0/",
            "source": "https://poly.pizza/m/87XZ2kDlAhh",
        },
        "path": "jeff",
        "name": "Jeff",
        "shortDescription": "Majestic Heavyweight",
        "description": "Introducing Jeff, the esteemed heavyweight champion of The Chicken Market. Jeff is not just any chicken; he is an embodiment of grandeur and presence. With his impressive physique, Jeff commands attention and admiration wherever he goes. Raised with meticulous care, Jeff's robust stature is a testament to his superior diet and relaxed lifestyle. Despite his size, Jeff is a gentle giant, exuding warmth and a laid-back charm that makes him an endearing companion. Adopting Jeff means welcoming a bundle of joy and personality into your home, offering an unparalleled companionship experience that only Jeff, the majestic heavyweight, can provide.",
        "imageCount": 3,
        "price": 99,
    },
    {
        "copyright": {
            "name": "Chick",
            "author": "Poly by Google",
            "authorLink": "https://poly.pizza/u/Poly%20by%20Google",
            "license": "CC-BY",
            "licenseLink": "https://creativecommons.org/licenses/by/3.0/",
            "source": "https://poly.pizza/m/7-uNQC5megf",
        },
        "path": "chickira",
        "name": "Chickira",
        "shortDescription": "The Dancing Diva",
        "description": "Introducing Chickira, the superstar of The Chicken Market. Much like her namesake, Chickira is not just any chicken; she is a vibrant and energetic companion known for her rhythmic movements and joyful demeanor. Chickira has been meticulously raised and trained to bring entertainment and companionship to a new level. Her innate sense of rhythm and her playful nature make her the life of any gathering. Whether she’s showing off her impressive dance moves or simply providing delightful company, Chickira is sure to bring endless joy to your home. Adopt Chickira today and let the dancing diva brighten your life with her boundless energy and charm.",
        "imageCount": 3,
        "price": 499,
    },
    {
        "copyright": {
            "name": "Rooster",
            "author": "Poly by Google",
            "authorLink": "https://poly.pizza/u/Poly%20by%20Google",
            "license": "CC-BY",
            "licenseLink": "https://creativecommons.org/licenses/by/3.0/",
            "source": "https://poly.pizza/m/6NTegstc5Jy",
        },
        "path": "eggward",
        "name": "Eggward",
        "shortDescription": "The Artisanal Rooster",
        "description": "Introducing Eggward, the most refined and artistically inclined rooster at The Chicken Market. Eggward brings a unique blend of sophistication and avian charm to any home. With his discerning taste and penchant for creativity, Eggward is not your average rooster. Raised with exceptional care and trained to appreciate the finer things in life, Eggward is known for his distinctive crow, reminiscent of a finely tuned instrument. His impeccable manners and cultured disposition make him an ideal companion for those who appreciate a touch of elegance in their lives. Experience the joy of adopting Eggward, and elevate your chicken companionship to a new level of artistry.",
        "imageCount": 3,
        "price": 249,
    },
    {
        "copyright": {
            "name": "Duck",
            "author": "jeremy",
            "authorLink": "https://poly.pizza/u/jeremy",
            "license": "CC-BY",
            "licenseLink": "https://creativecommons.org/licenses/by/3.0/",
            "source": "https://poly.pizza/m/2KHEgw1ztVI",
        },
        "path": "ducktor_who",
        "name": "Ducktor Who",
        "shortDescription": "What? How did a duck get here?",
        "description": "Introducing Ducktor Who, an enigmatic and intriguing addition to our lineup at The Chicken Markt. Despite our rigorous verification processes, we are as perplexed as you are about how Ducktor Who ended up on our website dedicated to chickens. However, we can assure you that this duck, wrapped in mystery and intrigue, is unlike any companion you’ve ever encountered.</br></br>Ducktor Who is not only a master of disguise but also brings an air of sophistication and intellect.His origins remain unknown, and his ability to seamlessly blend in with our esteemed chickens is both impressive and puzzling.While we can't fully explain his presence, we guarantee that Ducktor Who offers the same level of companionship and joy as our finest chickens. Adopt Ducktor Who today and embrace the delightful confusion and unique companionship that only a mysterious duck in disguise can provide.",
        "imageCount": 3,
        "price": 349
    },
    {
        "copyright": {
            "name": "Chicken Egg",
            "author": "sirkitree",
            "authorLink": "https://poly.pizza/u/sirkitree",
            "license": "CC-BY",
            "licenseLink": "https://creativecommons.org/licenses/by/3.0/",
            "source": "https://poly.pizza/m/0ylMw3Mzedx",
        },
        "path": "oleggvia",
        "name": "Ol-Egg-Via",
        "shortDescription": "The Future Star",
        "description": "Introducing Ol-Egg-via, the unhatched prodigy of The Chicken Markt. This exceptional egg is poised to become a legendary companion, embodying the potential of brilliance and charm. Named in honor of the acclaimed singer and songwriter Olivia Rodrigo, Ol-Egg-via Rodrigo represents the perfect blend of promise and talent, waiting to hatch and bring unparalleled joy into your life.</br></br>Ol-Egg-via Rodrigo is carefully nurtured in a controlled environment to ensure optimal health and development. With a pedigree of superior lineage, this egg is destined to become a remarkable chicken, possessing the intelligence, sociability, and charisma that our market is renowned for. By adopting Ol-Egg-via Rodrigo, you are investing in a future filled with companionship and delightful surprises, as this egg hatches into the star it is meant to be.",
        "imageCount": 1,
        "price": 129
    },
];